[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "pypdf2>=3.0.1",
    "torch>=2.7.0",
    "transformers>=4.52.3",
]
